dsa

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,39 +1,57 @@
 #!/usr/bin/env ruby
 # sync output
-export BUILD_DIR CACHE_DIR BIN_DIR PROFILE_PATH
+#!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir>
 
-echo "-----> Building qrencode"
+# fail fast
+set -e
 
-mkdir -p $HOME/qr
-BUILD_DIR=$HOME/qr
-mkdir -p $1/.profile.d
+# parse and derive params
+BUILD_DIR=$1
+CACHE_DIR=$2
 
-cat <<EOF >$BUILD_DIR/.profile.d/qrencoder.sh
-export PATH="$BUILD_DIR/bin:$PATH"
-export LD_LIBRARY_PATH="$BUILD_DIR/lib:$LD_LIBRARY_PATH"
-export INCLUDE_PATH="$BUILD_DIR/include:$INCLUDE_PATH"
-export CPATH="$INCLUDE_PATH"
-export CPPPATH="$INCLUDE_PATH"
-EOF
+# debug
+# set -x
+echo "-----> We are building libpixman and lippoppler in '$PWD' with contents:"
+ls -a
+echo "-----> Present PATH's:"
+echo "HOME: '$HOME'"
+echo "BUILD_DIR: '$BUILD_DIR'"
+echo "CACHE_DIR: '$CACHE_DIR'"
+echo "PATH: '$PATH'"
+echo "LD_RUN_PATH: '$LD_RUN_PATH'"
+echo "LD_LIBRARY_PATH: '$LD_LIBRARY_PATH'"
+echo "PKG_CONFIG_PATH: '$PKG_CONFIG_PATH'"
 
-export PATH="$BUILD_DIR/bin:$PATH"
-export LD_LIBRARY_PATH="$BUILD_DIR/lib:$LD_LIBRARY_PATH"
-export INCLUDE_PATH="$BUILD_DIR/include:$INCLUDE_PATH"
-export CPATH="$INCLUDE_PATH"
-export CPPPATH="$INCLUDE_PATH"
+# clean up leaking environment
+unset GIT_DIR
 
-curl http://fukuchi.org/works/qrencode/qrencode-3.2.0.tar.gz | tar xz
-cd qrencode-3.2.0; ./configure --prefix=$HOME/qr --enable-static --disable-shared; make; make install
-cd $1
-#export PATH=\"\$HOME/qr:$HOME/bin:/.bin:\$PATH\"
+if [[ "Darwin" == "$(uname)" ]]
+then
+    VENDORED_QRENCODE="$HOME/Code/heroku-qrencode-buildpack/vendor/qrencode" # Just for my local laptop testing
+else
+    VENDORED_QRENCODE="/app/vendor/qrencode"
+fi
 
+#Building qrencode
+echo "-----> Building qrencode ... BUILD_DIR: $BUILD_DIR // CACHE_DIR: $CACHE_DIR // PWD: $PWD"
+cd $BUILD_DIR
+curl -OL 'http://fukuchi.org/works/qrencode/qrencode-3.4.3.tar.gz'
+tar xzf qrencode-3.4.3.tar.gz
+cd qrencode-3.4.3
+CFLAGS='-fPIC -Wall -g -O2' CXXFLAGS='-fPIC -Wall -g -O2' png_CFLAGS='-fPIC -Wall -g -O2' ./configure --with-pic --enable-static --disable-shared --prefix=$VENDORED_QRENCODE
+make -j5
+make install
 
-$stdout.sync = true
-
-$:.unshift File.expand_path("../../lib", __FILE__)
-require "language_pack"
-require "language_pack/shell_helpers"
-
+echo "-----> Building runtime environment"
+cd $BUILD_DIR
+mkdir -p .profile.d
+echo "export VENDORED_QRENCODE=\"$VENDORED_QRENCODE\"" > .profile.d/libqrencode.sh
+echo "export PATH=\"\$HOME/vendor/qrencode/bin:\$PATH\"" >> .profile.d/libqrencode.sh
+echo "export LD_RUN_PATH=\"\$HOME/vendor/qrencode/lib:\$LD_RUN_PATH\"" >> .profile.d/libqrencode.sh
+echo "export LD_LIBRARY_PATH=\"\$HOME/vendor/qrencode/lib:\$LD_LIBRARY_PATH\"" >> .profile.d/libqrencode.sh
+echo "export PKG_CONFIG_PATH=\"\$HOME/vendor/qrencode/lib/pkgconfig:\$PKG_CONFIG_PATH\"" >> .profile.d/libqrencode.sh
+cat .profile.d/libqrencode.sh
 
 LanguagePack::Instrument.trace 'compile', 'app.compile' do
   if pack = LanguagePack.detect(ARGV[0], ARGV[1])
